# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
#ZSH_THEME="robbyrussell"
ZSH_THEME="powerlevel10k/powerlevel10k"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='nvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch $(uname -m)"

# Set personal aliases, overriding those provided by Oh My Zsh libs,
# plugins, and themes. Aliases can be placed here, though Oh My Zsh
# users are encouraged to define aliases within a top-level file in
# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
# - $ZSH_CUSTOM/aliases.zsh
# - $ZSH_CUSTOM/macos.zsh
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Sensitive dependencies
source ~/.config/hrc/.sensitive-rc

###### Android Dependencies ####################

#Java 8
export JAVA_HOME=/usr/lib/jvm/java-8u432-openjdk/
#Java 11
# export JAVA_HOME=/usr/lib/jvm/java-11.0.25-openjdk/

export ANDROID_HOME=~/Android/sd
export ANDROID_BUILD_TOOLS=~/Android/sdk/build-tools/34.0.0
export ANDROID_EMULATOR=~/Android/sdk/emulator
export NDK_HOME=~/Android/ndk/android-ndk-r27c
export GRADLE_USER_HOME=~/.gradle
export MAVEN_LOCAL_PATH=~/.m2/repository

export APACHE_MAVEN=~/Maven/apache-maven-3.9.9

# PATH Integration

#Java
export PATH=$JAVA_HOME/bin:$PATH
#Android
export PATH=$ANDROID_HOME:$ANDROID_HOME/tools:$ANDROID_EMULATOR:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$ANDROID_BUILD_TOOLS:$PATH

# Maven
export PATH=$APACHE_MAVEN/bin:$MAVEN_LOCAL_PATH:$PATH

################# /AndroidDependencies - END #####################

# Local Binaries as PATH #
export PATH="$HOME/.local/bin:$PATH"

# LESS config
export LESS="-Xr"

#Neovim
export PATH="$PATH:/opt/nvim-linux64-0.11.0/bin"

# Bat Cat
alias bat="batcat"

## NFS Mounting

alias mount_nfs_das_homelab_data="sudo mount -o resvport,rw -t nfs 10.0.0.251:/mnt/dasStorage/data "

## MC Aliases

alias mc_sheet="cat ~/Documents/GDocuments/Learning/Unix/mc/mc_sheet.md"
alias mce="mcedit"
alias mcv="mcview"

## FZF Aliases
alias search="fzf --preview=\"bat --color=always {}\""
alias search_img="fzf --preview=\"icat -w 50 {}\""

# Get IP
alias getIP="curl api.ipify.org"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Git Credential Manager
export GPG_TTY=$(tty)

# Eza
alias ls="eza"
alias ll="eza -alh"
alias tree="eza --tree"

# Android emulator default
alias android_emulator="emulator -avd Medium_Phone_API_35"

# Disk (NCDU)

alias cdisk="ncdu"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
